spring.application.name=aiagent

spring.datasource.url=jdbc:mysql://localhost:3306/aiagent_db
spring.datasource.username=root
spring.datasource.password=Today@20264321

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect